use_frameworks!

platform :ios, '9.0'

target 'NetworkGenericLibrary_Example' do
  pod 'NetworkGenericLibrary', :path => '../'

  target 'NetworkGenericLibrary_Tests' do
    inherit! :search_paths

    
  end
end
